add_test( [==[Get instance]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Get instance]==])
set_tests_properties( [==[Get instance]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Get instance]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Get UI Texture]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Get UI Texture]==])
set_tests_properties( [==[Get UI Texture]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Get UI Texture]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Get Tile Texture]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Get Tile Texture]==])
set_tests_properties( [==[Get Tile Texture]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Get Tile Texture]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Get Tile Surface]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Get Tile Surface]==])
set_tests_properties( [==[Get Tile Surface]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Get Tile Surface]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Load Texture]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Load Texture]==])
set_tests_properties( [==[Load Texture]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Load Texture]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Scenario: I can load and use textures]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can load and use textures]==])
set_tests_properties( [==[Scenario: I can load and use textures]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can load and use textures]==] PROPERTIES LABELS [==[[!mayfail];[engine]]==])
add_test( [==[I can create a Text widget]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[I can create a Text widget]==])
set_tests_properties( [==[I can create a Text widget]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[I can create a Text widget]==] PROPERTIES LABELS [==[[text];[ui];[widgets]]==])
add_test( [==[I can set text on a Text widget]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[I can set text on a Text widget]==])
set_tests_properties( [==[I can set text on a Text widget]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[I can set text on a Text widget]==] PROPERTIES LABELS [==[[text];[ui];[widgets]]==])
add_test( [==[I can change the font size of a Text widget]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[I can change the font size of a Text widget]==])
set_tests_properties( [==[I can change the font size of a Text widget]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[I can change the font size of a Text widget]==] PROPERTIES LABELS [==[[text];[ui];[widgets]]==])
add_test( [==[I can draw a Text widget]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[I can draw a Text widget]==])
set_tests_properties( [==[I can draw a Text widget]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[I can draw a Text widget]==] PROPERTIES LABELS [==[[text];[ui];[widgets]]==])
add_test( [==[I can't load the font]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[I can't load the font]==])
set_tests_properties( [==[I can't load the font]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[I can't load the font]==] PROPERTIES LABELS [==[[!mayfail];[ui];[widgets]]==])
add_test( [==[Create an destroy AudioMixer]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Create an destroy AudioMixer]==])
set_tests_properties( [==[Create an destroy AudioMixer]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Create an destroy AudioMixer]==] PROPERTIES LABELS [==[[audio];[engine]]==])
add_test( [==[Set the music volume]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Set the music volume]==])
set_tests_properties( [==[Set the music volume]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Set the music volume]==] PROPERTIES LABELS [==[[audio];[engine]]==])
add_test( [==[Set sound effects volume]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Set sound effects volume]==])
set_tests_properties( [==[Set sound effects volume]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Set sound effects volume]==] PROPERTIES LABELS [==[[audio];[engine]]==])
add_test( [==[Play music]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Play music]==])
set_tests_properties( [==[Play music]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Play music]==] PROPERTIES LABELS [==[[audio];[engine]]==])
add_test( [==[Scenario: I can change the music volume]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can change the music volume]==])
set_tests_properties( [==[Scenario: I can change the music volume]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can change the music volume]==] PROPERTIES LABELS [==[[!mayfail];[audio];[engine]]==])
add_test( [==[Scenario: I can change the sound effects volume]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can change the sound effects volume]==])
set_tests_properties( [==[Scenario: I can change the sound effects volume]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can change the sound effects volume]==] PROPERTIES LABELS [==[[audio];[engine]]==])
add_test( [==[Scenario: I can play music]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can play music]==])
set_tests_properties( [==[Scenario: I can play music]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can play music]==] PROPERTIES LABELS [==[[!mayfail];[audio];[engine]]==])
add_test( [==[Scenario: I can mute sounds]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can mute sounds]==])
set_tests_properties( [==[Scenario: I can mute sounds]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can mute sounds]==] PROPERTIES LABELS [==[[!mayfail];[audio];[engine]]==])
add_test( [==[You can use a TypeList like a safe linked list]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[You can use a TypeList like a safe linked list]==])
set_tests_properties( [==[You can use a TypeList like a safe linked list]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[You can use a TypeList like a safe linked list]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[TypeLists support random access]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[TypeLists support random access]==])
set_tests_properties( [==[TypeLists support random access]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[TypeLists support random access]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[Metaprogramming can be used to create strong abstractions]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Metaprogramming can be used to create strong abstractions]==])
set_tests_properties( [==[Metaprogramming can be used to create strong abstractions]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Metaprogramming can be used to create strong abstractions]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[Scenario: Observers listen to their Subject]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: Observers listen to their Subject]==])
set_tests_properties( [==[Scenario: Observers listen to their Subject]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: Observers listen to their Subject]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[Scenario: Observers can become expired]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: Observers can become expired]==])
set_tests_properties( [==[Scenario: Observers can become expired]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: Observers can become expired]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[I cannot call TransitiveModel::addObserver]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[I cannot call TransitiveModel::addObserver]==])
set_tests_properties( [==[I cannot call TransitiveModel::addObserver]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[I cannot call TransitiveModel::addObserver]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[Scenario: I can subscribe to all events]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can subscribe to all events]==])
set_tests_properties( [==[Scenario: I can subscribe to all events]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can subscribe to all events]==] PROPERTIES LABELS [==[[util]]==])
add_test( [==[Scenario: I can subscribe to specific events]==] /home/vroch/Projects/Cytopia/install/Cytopia_Tests [==[Scenario: I can subscribe to specific events]==])
set_tests_properties( [==[Scenario: I can subscribe to specific events]==] PROPERTIES WORKING_DIRECTORY /home/vroch/Projects/Cytopia/install/tests)
set_tests_properties( [==[Scenario: I can subscribe to specific events]==] PROPERTIES LABELS [==[[util]]==])
set( Cytopia_Tests_TESTS [==[Get instance]==] [==[Get UI Texture]==] [==[Get Tile Texture]==] [==[Get Tile Surface]==] [==[Load Texture]==] [==[Scenario: I can load and use textures]==] [==[I can create a Text widget]==] [==[I can set text on a Text widget]==] [==[I can change the font size of a Text widget]==] [==[I can draw a Text widget]==] [==[I can't load the font]==] [==[Create an destroy AudioMixer]==] [==[Set the music volume]==] [==[Set sound effects volume]==] [==[Play music]==] [==[Scenario: I can change the music volume]==] [==[Scenario: I can change the sound effects volume]==] [==[Scenario: I can play music]==] [==[Scenario: I can mute sounds]==] [==[You can use a TypeList like a safe linked list]==] [==[TypeLists support random access]==] [==[Metaprogramming can be used to create strong abstractions]==] [==[Scenario: Observers listen to their Subject]==] [==[Scenario: Observers can become expired]==] [==[I cannot call TransitiveModel::addObserver]==] [==[Scenario: I can subscribe to all events]==] [==[Scenario: I can subscribe to specific events]==])
