path_classifiers:
  library:
    - Cytopia_Resources
    - src/ThirdParty

extraction:
  cpp:
    prepare:
      packages:
        - libnoise-dev
    configure:
      command:
        - cmake -DENABLE_ANGELSCRIPT=OFF -DPACKAGE_MANAGER=pkgconfig -DBUILD_TEST=OFF .
