path_classifiers:
  library:
    - Cytopia_Resources
    - src/ThirdParty

extraction:
  cpp:
    prepare:
      packages:
        - libsdl2-dev 
        - libsdl2-image-dev 
        - libsdl2-ttf-dev 
        - libopenal-dev 
        - libvorbis-dev 
        - libpng-dev 
        - libnoise-dev
    configure:
      command:
        - cmake -DBUILD_TEST=OFF .
