path_classifiers:
  library:
    - Cytopia_Resources
    - src/ThirdParty

extraction:
  cpp:
    prepare:
      packages:
        - libnoise-dev
    configure:
      command:
        - cmake -DUSE_PACKAGE_MANAGER=OFF -DBUILD_TEST=OFF .
