path_classifiers:
  library:
    - Cytopia_Resources
    - src/ThirdParty

extraction:
  cpp:
    prepare:
      packages:
        - python3-virtualenv
    configure:
      command:
        - python3 -m venv test
        - cmake -DUSE_PMM=ON .