[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
once_cell = "1.20.2"

[dependencies.sdl2]
version = "0.37.0"
features = ["image", "ttf"]