# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia;/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install;Cytopia;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/archman/.conan/data/AngelScript/2.33/anotherfoxguy/stable/package/af0fbc5eb7376a4b9749db37a5c402b36d452909/;/home/archman/.conan/data/sdl2_ttf/2.0.15/bincrafters/stable/package/493101f71c56baf5f887b20b856bcc2fcfac3bff/;/home/archman/.conan/data/sdl2_image/2.0.4/bincrafters/stable/package/912f9df6f21dcaba1d4faa2f3880967dbf46baf9/;/home/archman/.conan/data/MofileReader/1.0.0/anotherfoxguy/stable/package/af0fbc5eb7376a4b9749db37a5c402b36d452909/;/home/archman/.conan/data/libnoise/1.0.1/anotherfoxguy/stable/package/af0fbc5eb7376a4b9749db37a5c402b36d452909/;/home/archman/.conan/data/OpenSSL/1.1.1a/conan/stable/package/9c111a8074926a7147291383e3d366f41bac77b3/;/home/archman/.conan/data/Catch2/2.8.0/catchorg/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/;/home/archman/.conan/data/sdl2/2.0.9/bincrafters/stable/package/4f5d4716151d6aadfc27eb131bd428ebd0f48cfc/;/home/archman/.conan/data/freetype/2.9.1/bincrafters/stable/package/ff441545227373e6cdb1ad421ac0c816c2580ee5/;/home/archman/.conan/data/libtiff/4.0.9/bincrafters/stable/package/3cea63dcd75faf305bb387fd56132f0eabf927e4/;/home/archman/.conan/data/libjpeg-turbo/1.5.2/bincrafters/stable/package/22f074d3c31c0c19b8fd4767975410f2faf68332/;/home/archman/.conan/data/libwebp/1.0.0/bincrafters/stable/package/9cb84c66d3f950b57b3b86cf56808eb02a5f27d8/;/home/archman/.conan/data/libpng/1.6.36/bincrafters/stable/package/3cea63dcd75faf305bb387fd56132f0eabf927e4/;/home/archman/.conan/data/bzip2/1.0.6/conan/stable/package/d666801fbcdc3fd37cf8b2a827d72e84b1878ff5/;/home/archman/.conan/data/zlib/1.2.11/conan/stable/package/761432f3453a17c960259b5b2605153e3bcffd7d/;/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/cmake;/home/archman/.conan/data/Catch2/2.8.0/catchorg/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2")
set(CPACK_NSIS_DISPLAY_NAME "Cytopia")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Cytopia")
set(CPACK_OUTPUT_CONFIG_FILE "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.14/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A pixel-art city building game")
set(CPACK_PACKAGE_FILE_NAME "Cytopia-0.2-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/JimmySnails/Cytopia")
set(CPACK_PACKAGE_ICON "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/build/msvc/cytopia.ico")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Cytopia")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Cytopia")
set(CPACK_PACKAGE_NAME "Cytopia")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Cytopia")
set(CPACK_PACKAGE_VERSION "0.2")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "2")
set(CPACK_RESOURCE_FILE_LICENSE "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/license.txt")
set(CPACK_RESOURCE_FILE_README "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.14/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "ON")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
