add_test( [==[Get instance]==] /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/Cytopia_Tests [==[Get instance]==])
set_tests_properties( [==[Get instance]==] PROPERTIES WORKING_DIRECTORY /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install)
set_tests_properties( [==[Get instance]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Get UI Texture]==] /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/Cytopia_Tests [==[Get UI Texture]==])
set_tests_properties( [==[Get UI Texture]==] PROPERTIES WORKING_DIRECTORY /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install)
set_tests_properties( [==[Get UI Texture]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Get Tile Texture]==] /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/Cytopia_Tests [==[Get Tile Texture]==])
set_tests_properties( [==[Get Tile Texture]==] PROPERTIES WORKING_DIRECTORY /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install)
set_tests_properties( [==[Get Tile Texture]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Get Tile Surface]==] /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/Cytopia_Tests [==[Get Tile Surface]==])
set_tests_properties( [==[Get Tile Surface]==] PROPERTIES WORKING_DIRECTORY /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install)
set_tests_properties( [==[Get Tile Surface]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Load Texture]==] /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/Cytopia_Tests [==[Load Texture]==])
set_tests_properties( [==[Load Texture]==] PROPERTIES WORKING_DIRECTORY /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install)
set_tests_properties( [==[Load Texture]==] PROPERTIES LABELS [==[[engine]]==])
add_test( [==[Scenario: I can load and use textures]==] /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install/Cytopia_Tests [==[Scenario: I can load and use textures]==])
set_tests_properties( [==[Scenario: I can load and use textures]==] PROPERTIES WORKING_DIRECTORY /home/archman/CodeProj/cpp_projects/cytopia-myfork/Cytopia/install)
set_tests_properties( [==[Scenario: I can load and use textures]==] PROPERTIES LABELS [==[[!mayfail];[engine]]==])
set( Cytopia_Tests_TESTS [==[Get instance]==] [==[Get UI Texture]==] [==[Get Tile Texture]==] [==[Get Tile Surface]==] [==[Load Texture]==] [==[Scenario: I can load and use textures]==])
