#ifndef CELL_HXX_
#define CELL_HXX_

#include <vector>
#include <map>
#include <cmath>

#include "SDL2/SDL.h"


#include "sprite.hxx"
#include "basics/point.hxx"
#include "basics/resources.hxx"


class Cell
{
public:
  Cell();
  Cell(Point isoCoordinates);
  ~Cell();

  void setSprite(Sprite* sprite);
  Sprite* getSprite();

  Point getCoordinates();

  void renderCell();

  void setNeighbors(std::vector<Cell*> neighbors);
  void drawSurroundingTiles(Point isoCoordinates);
  void determineTile();

  void increaseHeight();
  void decreaseHeight();

  void setTileID(int tileID);
  int getTileID();

  /** Check if given coordinates are in Cell */
  bool isInCell(Point clickedCoords);
  bool isInRect(Point clickedCoords);

  /** Sets the Z Coordinate (Drawing Order)*/
  void setZ(int z);
  /** Gets the Z Coordinate (Drawing Order)*/
  int getZ();

private:
  Point _isoCoordinates;
  Sprite* _sprite;

  std::vector<Cell*> _neighbors;
  SDL_Renderer* _renderer;
  SDL_Window* _window;

  bool hasElevatedNeighbors();

  int _heightOffset = 20; // Offset for Y Coordinate between two height levels
  int _tileID;
  int _maxCellHeight = 32;

  int _z;

  // Bitmask for neighbor positions
  // [ T B L R ]
  // [ 0 0 0 0 ]

  // Our neighbor tiles look like this
  // 2 5 8  
  // 1 X 7
  // 0 3 6

  
  enum elevatedTilePosition : unsigned int{
       NO_NEIGHBORS = 0x0,
       ELEVATED_TOP = 0x1,
       ELEVATED_BOTTOM = 0x2,
       ELEVATED_LEFT = 0x4,
       ELEVATED_RIGHT = 0x8,
       ELEVATED_TOP_LEFT = 0x10,
       ELEVATED_TOP_RIGHT = 0x20,
       ELEVATED_BOTTOM_LEFT = 0x40,
       ELEVATED_BOTTOM_RIGHT = 0x80,
  };


  unsigned int _elevatedTilePosition;


  // Map neighbor tile combinations to tile ID for keytiles.
  std::map<unsigned int, int> keyTileMap =
  {
    { NO_NEIGHBORS, 14 },
    { ELEVATED_TOP, 3 },
    { ELEVATED_BOTTOM, 5 },
    { ELEVATED_RIGHT, 1 },
    { ELEVATED_LEFT, 7 },
    { ELEVATED_BOTTOM_RIGHT, 2 },
    { ELEVATED_BOTTOM_LEFT, 8 },
    { ELEVATED_TOP_RIGHT, 0 },
    { ELEVATED_TOP_LEFT, 6 },

    { ELEVATED_TOP | ELEVATED_TOP_LEFT, 3 },
    { ELEVATED_TOP | ELEVATED_TOP_RIGHT, 3 },
    { ELEVATED_TOP | ELEVATED_TOP_RIGHT | ELEVATED_TOP_LEFT, 3 },
    { ELEVATED_TOP_LEFT | ELEVATED_TOP_RIGHT, 3 },

    { ELEVATED_BOTTOM | ELEVATED_BOTTOM_LEFT, 5 },
    { ELEVATED_BOTTOM | ELEVATED_BOTTOM_RIGHT, 5 },
    { ELEVATED_BOTTOM | ELEVATED_BOTTOM_RIGHT | ELEVATED_BOTTOM_LEFT, 5 },
    { ELEVATED_BOTTOM_LEFT | ELEVATED_BOTTOM_RIGHT, 5 },
  
    { ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT, 7},
    { ELEVATED_LEFT | ELEVATED_TOP_LEFT, 7},
    { ELEVATED_LEFT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_LEFT, 7},
    { ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_LEFT, 7},

    { ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT, 1 },
    { ELEVATED_RIGHT | ELEVATED_TOP_RIGHT, 1 },
    { ELEVATED_RIGHT | ELEVATED_TOP_RIGHT | ELEVATED_BOTTOM_RIGHT, 1 },
    { ELEVATED_BOTTOM_RIGHT | ELEVATED_TOP_RIGHT, 1 },

    { ELEVATED_TOP | ELEVATED_LEFT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT, 9 }, 
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_TOP_RIGHT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_RIGHT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_TOP_LEFT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_TOP_LEFT | ELEVATED_TOP_RIGHT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_LEFT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_RIGHT, 9 },
    { ELEVATED_TOP | ELEVATED_LEFT | ELEVATED_TOP_RIGHT | ELEVATED_TOP_RIGHT, 9 },

    { ELEVATED_TOP | ELEVATED_RIGHT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_TOP_LEFT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT | ELEVATED_TOP_LEFT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_TOP_RIGHT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_TOP_RIGHT | ELEVATED_TOP_LEFT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_TOP_RIGHT | ELEVATED_BOTTOM_RIGHT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_TOP_RIGHT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_RIGHT, 10 },
    { ELEVATED_TOP | ELEVATED_RIGHT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_RIGHT, 10 },

    { ELEVATED_BOTTOM | ELEVATED_RIGHT, 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_TOP_RIGHT, 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_BOTTOM_LEFT, 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT, 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT | ELEVATED_BOTTOM_LEFT , 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT | ELEVATED_TOP_RIGHT , 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_BOTTOM_RIGHT | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_RIGHT , 13 },
    { ELEVATED_BOTTOM | ELEVATED_RIGHT | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_RIGHT, 13 }, 
    { ELEVATED_BOTTOM | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_RIGHT, 13 }, 

    { ELEVATED_BOTTOM | ELEVATED_LEFT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_TOP_LEFT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_BOTTOM_RIGHT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_LEFT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT | ELEVATED_BOTTOM_RIGHT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_RIGHT, 11 },
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_RIGHT, 11},
    { ELEVATED_BOTTOM | ELEVATED_LEFT | ELEVATED_BOTTOM_RIGHT | ELEVATED_TOP_LEFT, 11 },

    //diagonal tiles - insert a block
    { ELEVATED_TOP_LEFT | ELEVATED_BOTTOM_RIGHT, 4},
    { ELEVATED_BOTTOM_LEFT | ELEVATED_TOP_RIGHT, 4},


    // special cases - elevate the tile
    { ELEVATED_RIGHT | ELEVATED_BOTTOM_LEFT, -1},
    { ELEVATED_RIGHT | ELEVATED_TOP_LEFT, -1},
    { ELEVATED_LEFT | ELEVATED_BOTTOM_RIGHT, -1},
    { ELEVATED_LEFT | ELEVATED_TOP_RIGHT, -1},
    { ELEVATED_TOP | ELEVATED_BOTTOM_LEFT, -1},
    { ELEVATED_TOP | ELEVATED_BOTTOM_RIGHT, -1},
    { ELEVATED_BOTTOM | ELEVATED_TOP_LEFT, -1},
    { ELEVATED_BOTTOM | ELEVATED_TOP_RIGHT, -1}

  };
};


#endif