---
name: Build Mac

on: [push, pull_request]

jobs:
  build-appleclang:
    env:
      SCCACHE_CACHE_SIZE: 500M
      CONAN_USER_HOME: /tmp/conan
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Prepare sccache timestamp
        id: sccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: sccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ~/Library/Caches/Mozilla.sccache
          key: macos-sccache-${{ steps.sccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            macos-sccache-

      - name: Cache conan
        uses: actions/cache@v1
        with:
          key: conan-root-${{ hashFiles('**/conanfile.txt.in') }}
          path: /tmp/conan

      - name: Install dependencies
        run: brew install conan sccache ninja
        shell: bash

      - name: Build
        run: |
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release .
          ninja
          mkdir -p bin/Cytopia.App/Resources/resources
          cp -pR data/resources bin/Cytopia.App/Contents/Resources/
          cp -pR data/resources bin/resources
          ninja copy_resources
          ninja package
          rm -rf bin/Cytopia.App/Contents/MacOS/resources
          rm -rf bin/Cytopia.App/Resources
          sccache --show-stats
        shell: bash

      - name: Test
        run: ctest -VV
        shell: bash

      - name: Clean Conan pkgs
        run: cmake -P ./cmake/pmm.cmake /Conan /Clean
        shell: bash
