name: Run SonarCloud Scan

on: [ push, pull_request ]

jobs:
  sonar-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.4
        if: env.SONAR_TOKEN != null
        with:
          submodules: true

      - name: Install dependencies
        if: env.SONAR_TOKEN != null
        run: |
          curl "https://raw.githubusercontent.com/AnotherFoxGuy/ci-scripts/main/install-cmake.sh" | sudo bash
          sudo apt-get update
          sudo apt-get -y install \
                  libsdl2-dev \
                  libsdl2-image-dev \
                  libsdl2-ttf-dev \
                  libnoise-dev \
                  libopenal-dev \
                  libvorbis-dev \
                  libpng-dev
        shell: bash

      - name: Install sonar scanner
        if: env.SONAR_TOKEN != null
        run: |
          export SONAR_SCANNER_VERSION=4.4.0.2170
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          export SONAR_SCANNER_OPTS="-server"

          curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
        shell: bash

      - name: Build
        if: env.SONAR_TOKEN != null
        run: |
          cmake -DPACKAGE_MANAGER=pkgconfig -DENABLE_ANGELSCRIPT=OFF .
          build-wrapper-linux-x86-64 --out-dir bw-output make -j4
        shell: bash

      - name: Build
        if: env.SONAR_TOKEN != null
        run: |
          sonar-scanner \
            -Dsonar.organization=cytopia \
            -Dsonar.projectKey=cytopia \
            -Dsonar.sources=. \
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.host.url=https://sonarcloud.io
        shell: bash
